Alias "/__deploy/" "/var/www/global-daisho-deployer/"

<Directory "/var/www/global-daisho-deployer/">
    Options -Indexes
    AllowOverride None
    DirectoryIndex index.php

    AuthType Basic
    AuthName "GLOBAL DAISHO Deploy"
    AuthUserFile /etc/apache2/global-daisho-deployer.htpasswd

    Require valid-user

    <FilesMatch "^(?!index\.php$)">
        Require all denied
    </FilesMatch>
</Directory>
