CREATE TABLE IF NOT EXISTS crm_sheet_tests (
    source_key VARCHAR(191) PRIMARY KEY,
    experiment_number INT UNSIGNED NOT NULL,
    test_id BIGINT UNSIGNED NULL UNIQUE,
    source_snapshot MEDIUMTEXT NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
